# Generated by Django 4.2.16 on 2024-10-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('news', 'News')], default='news', max_length=100)),
                ('alignment', models.CharField(choices=[('assess', 'Needs Assessment'), ('western', 'Western'), ('non-western', 'Non-Western'), ('mixed', 'Mixed')], default='assess', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Website'), ('rss', 'RSS'), ('youtube', 'Youtube'), ('rumble', 'Rumble'), ('odysee', 'Odysee')], default='website', max_length=100)),
                ('url', models.URLField(unique=True)),
                ('keyword_search_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword_search_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltest.organization')),
            ],
        ),
    ]
