# Generated by Django 4.2.16 on 2024-10-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='language',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('linktree', 'Linktree'), ('rss', 'RSS'), ('youtube', 'Youtube'), ('rumble', 'Rumble'), ('odysee', 'Odysee')], default='website', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='alignment',
            field=models.CharField(choices=[('assess', 'TBD'), ('western', 'Western'), ('non-western', 'Non-Western'), ('mixed', 'Mixed')], default='assess', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('ngo', 'NGO')], default='news', max_length=100),
        ),
    ]
