# Generated by Django 4.2.16 on 2024-10-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0002_link_language_alter_link_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stub', models.CharField(max_length=20, unique=True)),
                ('lang', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('rss', 'RSS'), ('linktree', 'Linktree'), ('fb', 'facebook'), ('x', 'X'), ('insta', 'Instagram'), ('youtube', 'Youtube'), ('rumble', 'Rumble'), ('odysee', 'Odysee')], default='website', max_length=100),
        ),
        migrations.CreateModel(
            name='OrganizationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltest.language')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltest.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='language',
            field=models.ForeignKey(blank=True, default='en', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltest.language'),
        ),
    ]
