# Generated by Django 4.2.16 on 2024-10-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0003_language_link_name_alter_link_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltest.language'),
        ),
    ]
