# Generated by Django 4.2.16 on 2024-10-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0004_alter_link_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltest.language'),
        ),
    ]
