# Generated by Django 4.2.16 on 2024-10-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0005_alter_link_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltest.language'),
        ),
        migrations.AlterField(
            model_name='link',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
