# Generated by Django 4.2.16 on 2024-10-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0006_link_lang_alter_link_language_alter_link_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='lang',
        ),
    ]
