# Generated by Django 4.2.16 on 2024-10-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0007_remove_link_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='stub',
            new_name='iso',
        ),
        migrations.AlterField(
            model_name='link',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltest.language'),
        ),
    ]
