# Generated by Django 4.2.16 on 2024-10-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0008_rename_stub_language_iso_alter_link_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='language',
        ),
    ]
