# Generated by Django 4.2.16 on 2024-10-26 23:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modeltest', '0010_alter_organizationlanguage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('mainsite', 'Main Website'), ('website', 'Website'), ('rss', 'RSS'), ('linktree', 'Linktree'), ('fb', 'Facebook'), ('x', 'X'), ('insta', 'Instagram'), ('youtube', 'Youtube'), ('rumble', 'Rumble'), ('odysee', 'Odysee')], default='mainsite', max_length=100),
        ),
    ]
