# Generated by Django 5.1.2 on 2024-10-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesearch', '0002_link_url_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url_suffix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
